parameters:
    orbitale_translation.default_layout: OrbitaleTranslationBundle:Translation:_layout.html.twig
    orbitale_translation.translator.class: Orbitale\Bundle\TranslationBundle\Translation\Translator
    orbitale_translation.loader: Orbitale\Bundle\TranslationBundle\Translation\TranslationLoader
    orbitale_translation.extractor.class: Orbitale\Bundle\TranslationBundle\Translation\Extractor
    orbitale_translation.output_directory: ~

    # Overrides the Symfony2's translator. Disabled only when removing "import resources" for this file from config.yml
    translator.class: %orbitale_translation.translator.class%
