orbitale_translation_adminlist:
    path:      /translations/
    defaults:
        _controller: OrbitaleTranslationBundle:Translation:adminList

orbitale_translation_export:
    path:      /translations/export/{locale}
    defaults:
        _controller: OrbitaleTranslationBundle:Translation:export
        locale: null
    requirements:
        locale: "[a-z]*"

orbitale_translation_edit:
    path:      /translations/{locale}/{domain}
    defaults:
        _controller: OrbitaleTranslationBundle:Translation:edit
