services:
    translation.loader.db:
        class: %orbitale_translation.loader%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: translation.loader, alias: db }

    orbitale_translator:
        class: %orbitale_translation.translator.class%
        arguments:
            - @service_container
            - @translator.selector
            - []
            - {cache_dir: %kernel.cache_dir%/translations, debug: %kernel.debug%}

    orbitale.translation.extractor:
        class: %orbitale_translation.extractor.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @translation.writer
            - %kernel.root_dir%
            - %kernel.cache_dir%
            - %orbitale_translation.output_directory%

    orbitale_translation.listener.flush_translations:
        class: Orbitale\Bundle\TranslationBundle\Listeners\FlushTranslations
        arguments:
            - @orbitale_translator
        tags:
            - { name: kernel.event_subscriber }

    orbitale_translation.listener.locale:
        class: Orbitale\Bundle\TranslationBundle\Listeners\LocaleListener
        arguments:
            - "%kernel.default_locale%"
        tags:
            - { name: kernel.event_subscriber }

    orbitale_translation.twig.extension:
        class: Orbitale\Bundle\TranslationBundle\Twig\TranslationExtension
        arguments:
            - @orbitale_translator
        tags:
            - { name: twig.extension }

    orbitale_translation.data_collector:
        class: Orbitale\Bundle\TranslationBundle\DataCollector\TranslationDataCollector
        arguments:
            - @orbitale_translator
        tags:
            - { name: data_collector, template: "@OrbitaleTranslation/Collector/translation", id: orbitale_translation }
