services:

    orbitale_tools.admin.translations:
        class: Orbitale\Bundle\TranslationBundle\Admin\TranslationAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Translations", label: "Translations" }
        arguments:
            - ~
            - Orbitale\Bundle\TranslationBundle\Entity\Translation
            - ~
